os: windows
sudo: required
language: node_js
node_js:
  - '10'
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: dev
      install:
        - npm install
      script:
        - source build.sh
